name: run cypress e2e-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies installation
        uses: bahmutov/npm-install@v1
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: npm start
          wait-on: 'http://localhost:3000'
          project: ./cypress